dist: trusty
sudo: required

language: generic

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="CoqEAL"
  matrix:
  - COQ_IMAGE="mathcomp/mathcomp:1.7.0-coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp:1.7.0-coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp:1.7.0-coq-8.9"
  - COQ_IMAGE="mathcomp/mathcomp:1.7.0-coq-dev"
  - COQ_IMAGE="mathcomp/mathcomp-dev:coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp-dev:coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp-dev:coq-8.9"
  - COQ_IMAGE="mathcomp/mathcomp-dev:coq-dev"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    # pass --login so we can use “travis_retry” and omit “opam config exec --”
    # and this bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    : Updating OPAM cache
    opam update -y
    : Installing OPAM deps
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    opam install -y -j ${NJOBS} coq-paramcoq
    if [[ "${COQ_IMAGE}" =~ "mathcomp-dev" ]]; then
      opam install -y -j ${NJOBS} --ignore-constraints-on=coq-mathcomp-ssreflect,coq-mathcomp-algebra coq-mathcomp-multinomials
    else
      opam install -y -j ${NJOBS} coq-mathcomp-multinomials 
    fi
    opam config list
    opam repo list
    opam list
    : done" install

script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    ( pushd theory && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} all && make install && popd )
    ( pushd refinements && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} && make install && popd )
    : done" script
- docker stop COQ  # optional
- echo -en 'travis_fold:end:script\\r'
