os: linux

services:
- docker

branches:
  only:
  - master

env:
  global:
  - NJOBS="2"
  - CONTRIB="coqeal"
  - OPAMYES=yes
  matrix:
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.7"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.8"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.9"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.10"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.11"

install:
- docker pull ${DOCKERIMAGE}
- docker tag  ${DOCKERIMAGE} ci:current
- docker run  --env=OPAMYES --init -id --name=CI -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB} -w /home/coq/${CONTRIB} ci:current
- docker exec CI /bin/bash --login -c "opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev"
- docker exec CI /bin/bash --login -c "opam pin add -n coq-${CONTRIB} ."
- docker exec CI /bin/bash --login -c "opam install --deps-only coq-${CONTRIB}"

script:
- docker exec CI /bin/bash --login -c "opam install ."
