name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:1.11.0-coq-8.7'
          - 'mathcomp/mathcomp:1.11.0-coq-8.8'
          - 'mathcomp/mathcomp:1.11.0-coq-8.9'
          - 'mathcomp/mathcomp:1.11.0-coq-8.10'
          - 'mathcomp/mathcomp:1.11.0-coq-8.11'
          - 'mathcomp/mathcomp:1.11.0-coq-8.12'
          - 'mathcomp/mathcomp:1.12.0-coq-8.10'
          - 'mathcomp/mathcomp:1.12.0-coq-8.11'
          - 'mathcomp/mathcomp:1.12.0-coq-8.12'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-coqeal.opam'
          custom_image: ${{ matrix.image }}
          custom_script: |
            startGroup Print opam config
              opam config list; opam repo list; opam list
            endGroup
            startGroup Build dependencies
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install -y -j 2 $PACKAGE --deps-only
            endGroup
            startGroup Build
              opam install -y -v -j 2 $PACKAGE
              opam list
            endGroup
            startGroup Workaround permission issue
              sudo chown -R coq:coq .
            endGroup
            startGroup Uninstallation test
              opam remove $PACKAGE
            endGroup
      - name: Revert permissions
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
